name: Build

on: [pull_request]

jobs:
  build:
    name: 🏭 Build all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build all packages
        run: yarn build

      - run: yarn lint:check && yarn format:check
