name: Publish to NPM

on:
  push:
    tags: 
      - '**-[0-9].[0-9].[0-9]'
      - '**-[0-9].[0-9].[0-9]-*'
  release:
    tags: 
      - '**-[0-9].[0-9].[0-9]'
      - '**-[0-9].[0-9].[0-9]-*'
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    # Source checkout
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    # Setting Node environment
    - name: Setting up Node environment
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    # Environment configuration
    - name: Preparing environment for release
      run: | 
        VERSION=$(echo $GITHUB_REF_NAME | sed 's/^.*[A-Za-z]-//g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "CONSTRUCT=$(echo $GITHUB_REF_NAME | sed "s/-${VERSION}//g")" >> $GITHUB_ENV
    # Release process
    - name: Release
      working-directory: packages/${{env.CONSTRUCT}}
      run: | 
        echo ${{env.CONSTRUCT}}
        npm ci
        git config --global user.name "Automated NPM Release"
        git config --global user.email "sysadmin+npm-deploy@aligent.com.au"
        npm version $VERSION --allow-same-version --workspace "@aligent/cdk-${package}"
        npm run build --workspace "@aligent/cdk-${package}"
        npm test --workspace "@aligent/cdk-${package}" --if-present
    #     npm publish --access public --workspace "@aligent/cdk-${package}"
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - run: git push
    #   env:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}