name: Publish to NPM

env:
  package: basic-auth

on:
  release:
    tags:
      - '$package-*' # Push events to matching basic-auth-*, i.e. basic-auth-1.12.6

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: git config --global user.name "Automated NPM Release"
    - run: git config --global user.email "sysadmin+npm-deploy@aligent.com.au"
    - run: npm version ${{ github.event.release.tag_name }}#"$package-" --allow-same-version # strip the package out of the release name
    - run: npm run build
    - run: npm test
    - run: npm publish --access public --workspace "@aligent/cdk-${package}" --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
